"""empty message

Revision ID: 6627c340ae07
Revises: a6cfb6f36035
Create Date: 2026-07-27 11:38:38.006340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6627c340ae07'
down_revision = 'a6cfb6f36035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('total_races', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    # ### end Alembic commands ###
