"""empty message

Revision ID: 91358c767eeb
Revises: 1b3157f6f5c4
Create Date: 2026-07-07 02:07:32.410596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91358c767eeb'
down_revision = '1b3157f6f5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_in_room', schema=None) as batch_op:
        batch_op.alter_column('socket_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_in_room', schema=None) as batch_op:
        batch_op.alter_column('socket_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
