"""empty message

Revision ID: 998f7e161ecb
Revises: 9f6f3bad6e72
Create Date: 2026-06-28 19:50:40.158485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998f7e161ecb'
down_revision = '9f6f3bad6e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('num_of_plrs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_plrs', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
