"""empty message

Revision ID: 99a5af1f67cc
Revises: 3a8b3ac936c9
Create Date: 2026-06-28 01:08:42.143703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a5af1f67cc'
down_revision = '3a8b3ac936c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_plrs', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('num_of_plrs')

    # ### end Alembic commands ###
