"""empty message

Revision ID: 9f6f3bad6e72
Revises: 99a5af1f67cc
Create Date: 2026-06-28 19:11:43.408310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6f3bad6e72'
down_revision = '99a5af1f67cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_in_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('car_color', sa.String(), nullable=False),
    sa.Column('car_filter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_code'], ['room.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_in_room')
    # ### end Alembic commands ###
