"""empty message

Revision ID: d9c1aa2dbfe2
Revises: 998f7e161ecb
Create Date: 2026-07-03 22:25:14.314943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c1aa2dbfe2'
down_revision = '998f7e161ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_in_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socket_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['socket_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_in_room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('socket_id')

    # ### end Alembic commands ###
